### ISSUE TITLE
exec-based credential plugin is not working

### ISSUE THREAD

**Issue by losil** [alekc/terraform-provider-kubectl#134] opened 2024-05-07 07:07 UTC
In the past we were successfully using `gavinbunney/kubectl` in combination with Azure AD enabled AKS clusters. Because local accounts are disabled, we have to rely on authentication with kubelogin. Since `gavinbunney/kubectl` is not maintained anymore, we'd like to use your provider. Unfortunately we are running into issues regarding the exec plugin. 

During the first test the resources got successfully applied with a `terraform apply`. But I couldn't see the recently applied resources in the AKS cluster. I then observed that the resources got applied to the context which was active in my local kubeconfig file. This is a local cluster and kubelogin would not work. To my understanding this should be avoided with the provider configuration `load_config_file = false`. I then removed my local kubeconfig file from `~/.kube/config` and retried `terraform apply`. With this setup the apply fails with the error that the Kubernetes rest client could not connect to localhost. 
The identically configuration is working with the provider `gavinbunney/kubectl`. So it seems that your provider is handling the `exec` plugin wrong.

see configuration and logs below:

```hcl
terraform {
  required_providers {
    kubectl = {
      source  = "alekc/kubectl"
      version = "2.0.4"
    }
  }
}
```

```hcl
provider "kubectl" {
  apply_retry_count      = 5
  host                   = module.aks.aks_api_host
  cluster_ca_certificate = module.aks.aks_cluster_ca
  load_config_file       = false

  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "kubelogin"
    args = [
      "get-token",
      "--login",
      "spn",
      "--environment",
      "AzurePublicCloud",
      "--tenant-id",
      var.tenant_id,
      "--server-id",
      var.aad_server_application_id,
      "--client-id",
      var.client_id,
      "--client-secret",
      var.client_secret
    ]
  }
}
```

```
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.aks.kubectl_manifest.cert_manager_cluster_issuer_production: Creating...
module.aks.kubectl_manifest.cert_manager_cluster_issuer_staging: Creating...
╷
│ Error: deagxacme-staging failed to create kubernetes rest client for update of resource: Get "http://localhost/api?timeout=32s": dial tcp [::1]:80: connect: connection refused
│
│   with module.aks.kubectl_manifest.cert_manager_cluster_issuer_staging,
│   on ../../kubernetes.tf line 126, in resource "kubectl_manifest" "cert_manager_cluster_issuer_staging":
│  126: resource "kubectl_manifest" "cert_manager_cluster_issuer_staging" {
│
╵
╷
│ Error: deagxacme-production failed to create kubernetes rest client for update of resource: Get "http://localhost/api?timeout=32s": dial tcp [::1]:80: connect: connection refused
│
│   with module.aks.kubectl_manifest.cert_manager_cluster_issuer_production,
│   on ../../kubernetes.tf line 143, in resource "kubectl_manifest" "cert_manager_cluster_issuer_production":
│  143: resource "kubectl_manifest" "cert_manager_cluster_issuer_production" {
│
╵
```

**Comment by jpdoria** [comment] 2024-05-28 05:10
I'm getting this error, too, but on AWS.

```bash
Error: failed to create kubernetes rest client for read of resource: Get "https://foobar.gr7.us-east-1.eks.amazonaws.com/api?timeout=32s": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
with kubectl_manifest.node_local_dns_cache[0]
on kubectl.tf line 7, in resource "kubectl_manifest" "node_local_dns_cache":
resource "kubectl_manifest" "node_local_dns_cache" {
```

My `kubectl` provider is configured like this (`kubernetes` and `helm` are working fine), and the version I'm using:

```hcl
provider "kubernetes" {
  host                   = module.eks.cluster_endpoint
  cluster_ca_certificate = base64decode(var.cluster_certificate_authority_data)

  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    args        = ["eks", "get-token", "--cluster-name", lower(var.tags.project)]
  }
}

provider "helm" {
  kubernetes {
    host                   = module.eks.cluster_endpoint
    cluster_ca_certificate = base64decode(var.cluster_certificate_authority_data)

    exec {
      api_version = "client.authentication.k8s.io/v1beta1"
      command     = "aws"
      args        = ["eks", "get-token", "--cluster-name", lower(var.tags.project)]
    }
  }
}

provider "kubectl" {
  host                   = module.eks.cluster_endpoint
  cluster_ca_certificate = base64decode(var.cluster_certificate_authority_data)
  load_config_file       = false
  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    args        = ["eks", "get-token", "--cluster-name", lower(var.tags.project)]
  }
}

```

```hcl
terraform {
  required_version = ">= 1.8.4"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 4.65.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = ">= 2.20.0"
    }
    helm = {
      source  = "hashicorp/helm"
      version = ">= 2.5.1"
    }
    kubectl = {
      source  = "alekc/kubectl"
      version = "~> 2.0"
    }
  }
}
```

**Comment by vkice-at-ocp** [comment] 2024-06-04 18:25
Same issue as you both which identical configs, looks to be an issue with this provider specifically like you mention.

**Comment by jpalko** [comment] 2024-06-27 07:02
I have not had issues with kubectl provider, configs below:
```
terraform {

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
 
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.0"
    }

    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.0"
    }

    kubectl = {
      source  = "alekc/kubectl"
      version = "2.0.4"
    }
  }

  required_version = "~> 1.5.0"
}
```
```
provider "kubectl" {
  alias                  = "eks"
  apply_retry_count      = 5
  host                   = module.eks.cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)
  load_config_file       = false

  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    args = ["eks", "get-token", "--cluster-name", module.eks.cluster_name]
  }
```

**Comment by cmartell-at-ocp** [comment] 2024-07-10 23:52
We actually figured out our issue: we are passing a `role_arn` to the AWS provider. By default, the `exec` command was just trying to use the role attached to our Atlantis pod. Worked around this with the follow configuration:

```
data "aws_caller_identity" "this" {}
data "aws_iam_session_context" "this" {
  arn = data.aws_caller_identity.this.arn
}

provider "kubectl" {
  host                   = data.aws_eks_cluster.this.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.this.certificate_authority[0].data)
  load_config_file       = false
  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    args        = ["eks", "get-token", "--cluster-name", var.eks_cluster_name, "--role-arn", data.aws_iam_session_context.this.issuer_arn]
    command     = "aws"
  }
}
```

**Comment by Kartoshnikov** [comment] 2024-07-22 08:50
Doesn't work as well.
EKS 1.28

```
terraform {
  required_version = ">= 1.5.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.45"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.16"
    }
    kubectl = {
      source  = "alekc/kubectl"
      version = "~> 2.0"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.7"
    }
    time = {
      source = "hashicorp/time"
      version = "~> 0.9"
    }
  }
}
```
```
provider "kubectl" {
  host                   = module.eks.cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)
  load_config_file       = false
  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    args        = ["eks", "get-token", "--cluster-name", module.eks.cluster_name]
    command     = "aws"
  }
}
```
Executed using
```
AWS_PROFILE=PROFILE terragrunt plan -out plan
```

**Comment by alekc** [comment] 2024-07-23 08:06
hmm, could you try for a test to hardcode host value changing it from the `module.eks.cluster_endpoint` to the text endpoint value? I wonder why its trying to connect to the localhost as an endpoint

**Comment by Kartoshnikov** [comment] 2024-07-23 11:36
> alekc/kubectl

I did try to hardcode the eks cluster endpoint and it doesn't make any defference as if it doens't respect `host` field at all.

Another weird behaviour I spotted while was trying was that the provider works only if I had configured my k8s contexts correctly. So it seems like it relies not on the provider configuration but rather on the local kubectl configuration.
I ran the same command in a docker container without kubectl installed using only `.aws` from the host machine and it didn't work either.

**Comment by sinkr** [comment] 2024-07-24 14:32
What about just mimic'ing how the Helm provider works and is implemented?  It's almost the same config and doesn't need all these gyrations to work correctly.

Right now, I have to make sure my current kubectl context is correct and that's misleading, if not dangerous.  I also take an extra step to point to a temporary kubeconfig I have to generate for each cluster change "just in case."

Please fix this.

**Comment by alekc** [comment] 2024-07-28 07:32
I cannot reproduce the issue related to hosts. Tests so far:
```
 terraform -v  
EKS 1.27               
Terraform v1.8.5
on darwin_arm64
+ provider registry.terraform.io/alekc/kubectl v2.0.4

Your version of Terraform is out of date! The latest version
is 1.9.3. You can update by downloading from https://www.terraform.io/downloads.html
```

Given the code with a wrong host, it uses the wrong one as expected

```hcl
terraform {
  required_providers {
    kubectl = {
      source = "alekc/kubectl"
      version = "2.0.4"
    }
  }
}

provider "kubectl" {
#   host                   = local.host
  host = "https://example.com"
  cluster_ca_certificate = local.ca

  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    args        = ["eks", "get-token", "--cluster-name", local.cluster_name]
  }
}

resource "kubectl_manifest" "example" {
  yaml_body = <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
  namespace: default
type: Opaque
data:
  username: bm90YWRtaW4K # base64 encoded string for "notadmin"
stringData:
  username: admin # required field for kubernetes.io/basic-auth
  password: t0p-Secret # required field for kubernetes.io/basic-auth
EOF
}
```
(Note, the actual exec phase if you start from a blank state, will happens only when you type yes in the apply, so during the actual apply of the resources). 
```
➜ terraform apply -auto-approve

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # kubectl_manifest.example will be created
  + resource "kubectl_manifest" "example" {
      + api_version             = "v1"
      + apply_only              = false
      + field_manager           = "kubectl"
      + force_conflicts         = false
      + force_new               = false
      + id                      = (known after apply)
      + kind                    = "Secret"
      + live_manifest_incluster = (sensitive value)
      + live_uid                = (known after apply)
      + name                    = "secret-basic-auth"
      + namespace               = "default"
      + server_side_apply       = false
      + uid                     = (known after apply)
      + validate_schema         = true
      + wait_for_rollout        = true
      + yaml_body               = (sensitive value)
      + yaml_body_parsed        = <<-EOT
            apiVersion: v1
            data: (sensitive value)
            kind: Secret
            metadata:
              name: secret-basic-auth
              namespace: default
            stringData: (sensitive value)
            type: Opaque
        EOT
      + yaml_incluster          = (sensitive value)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
kubectl_manifest.example: Creating...
╷
│ Error: default/secret-basic-auth failed to create kubernetes rest client for update of resource: Get "https://example.com/api?timeout=32s": getting credentials: exec: executable aws failed with exit code 253
│ 
│   with kubectl_manifest.example,
│   on main.tf line 31, in resource "kubectl_manifest" "example":
│   31: resource "kubectl_manifest" "example" {
│ 
╵
```

Putting a proper host BUT not providing any means to authenticate against AWS
```hcl
terraform {
  required_providers {
    kubectl = {
      source = "alekc/kubectl"
      version = "2.0.4"
    }
  }
}

provider "kubectl" {
  host                   = local.host
  cluster_ca_certificate = local.ca

  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    args        = ["eks", "get-token", "--cluster-name", local.cluster_name]
  }
}

resource "kubectl_manifest" "example" {
  yaml_body = <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
  namespace: default
type: Opaque
data:
  username: bm90YWRtaW4K # base64 encoded string for "notadmin"
stringData:
  username: admin # required field for kubernetes.io/basic-auth
  password: t0p-Secret # required field for kubernetes.io/basic-auth
EOF
}
```
```
➜ terraform apply -auto-approve


Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # kubectl_manifest.example will be created
  + resource "kubectl_manifest" "example" {
      + api_version             = "v1"
      + apply_only              = false
      + field_manager           = "kubectl"
      + force_conflicts         = false
      + force_new               = false
      + id                      = (known after apply)
      + kind                    = "Secret"
      + live_manifest_incluster = (sensitive value)
      + live_uid                = (known after apply)
      + name                    = "secret-basic-auth"
      + namespace               = "default"
      + server_side_apply       = false
      + uid                     = (known after apply)
      + validate_schema         = true
      + wait_for_rollout        = true
      + yaml_body               = (sensitive value)
      + yaml_body_parsed        = <<-EOT
            apiVersion: v1
            data: (sensitive value)
            kind: Secret
            metadata:
              name: secret-basic-auth
              namespace: default
            stringData: (sensitive value)
            type: Opaque
        EOT
      + yaml_incluster          = (sensitive value)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
kubectl_manifest.example: Creating...
╷
│ Error: default/secret-basic-auth failed to create kubernetes rest client for update of resource: Get "https://XXXXXX.gr7.us-east-1.eks.amazonaws.com/api?timeout=32s": getting credentials: exec: executable aws failed with exit code 253
│ 
│   with kubectl_manifest.example,
│   on main.tf line 30, in resource "kubectl_manifest" "example":
│   30: resource "kubectl_manifest" "example" {
│ 
╵
```

Once I provide the terraform with a mean to auth itself by providing AWS_PROFILE=xxx it works
```
➜ terraform apply -auto-approve

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # kubectl_manifest.example will be created
  + resource "kubectl_manifest" "example" {
      + api_version             = "v1"
      + apply_only              = false
      + field_manager           = "kubectl"
      + force_conflicts         = false
      + force_new               = false
      + id                      = (known after apply)
      + kind                    = "Secret"
      + live_manifest_incluster = (sensitive value)
      + live_uid                = (known after apply)
      + name                    = "secret-basic-auth"
      + namespace               = "default"
      + server_side_apply       = false
      + uid                     = (known after apply)
      + validate_schema         = true
      + wait_for_rollout        = true
      + yaml_body               = (sensitive value)
      + yaml_body_parsed        = <<-EOT
            apiVersion: v1
            data: (sensitive value)
            kind: Secret
            metadata:
              name: secret-basic-auth
              namespace: default
            stringData: (sensitive value)
            type: Opaque
        EOT
      + yaml_incluster          = (sensitive value)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
kubectl_manifest.example: Creating...
kubectl_manifest.example: Creation complete after 1s [id=/api/v1/namespaces/default/secrets/secret-basic-auth]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

Context is being respected as well (setting it to a local kind and running on AWS). 

Also, just to remind, this provider has been forked from gavinbunney, and the only bits changed related to the actual provider (aka kubernetes client) are related to the introduction of tls and proxy.

**Comment by Kartoshnikov** [comment] 2024-07-30 10:04
@alekc 
Have you run it from the inside of a docker container without `kubectl` command or a context?
I used `devopsinfra/docker-terragrunt:aws-tf-1.8.4-tg-0.58.12` container.

The exec command is as follows:
`docker run -v $PWD:/app -v ~/.aws:/root/.aws -it --rm --entrypoint '' devopsinfra/docker-terragrunt:aws-tf-1.8.4-tg-0.58.12 bash`

And I did use `AWS_PROFILE` env var for terragrunt.

I do understand, that this project is a fork of gavinbunney one and it is supposed to have the same authentication mechanisms. Why then after the provider is changed back to gavinbunney whiout the code changes it (plan) works right away? What am I missing?

Could you please try creating a resource using gavinbunney provider and then change it to this one (alekc) and run plan again?
In my case the alekc provider simply use my kubectl context and doesn't respect the provider configuration at all.

**Comment by alekc** [comment] 2024-07-30 10:55
Still working even from container
```
docker run -v $PWD:/app -v ~/.aws:/root/.aws -it --rm --entrypoint '' devopsinfra/docker-terragrunt:aws-tf-1.8.4-tg-0.58.12 bash
Unable to find image 'devopsinfra/docker-terragrunt:aws-tf-1.8.4-tg-0.58.12' locally
aws-tf-1.8.4-tg-0.58.12: Pulling from devopsinfra/docker-terragrunt
323c9982d561: Pulling fs layer 
5659716b959c: Pulling fs layer 
93413499ce7c: Pulling fs layer 
a8b1c5f80c2d: Pulling fs layer 
8a4aa43b0c7b: Pulling fs layer 
b7171328d619: Pulling fs layer 
639a804c8046: Pulling fs layer 
93413499ce7c: Download complete 
fb88742579f2: Download complete 
4311e5e615f5: Download complete 
05de69757454: Download complete 
72fbb563752d: Download complete 
caa41d86f058: Download complete 
b2691a2caeef: Download complete 
778ae51b9814: Download complete 
12a9055ddffc: Download complete 
e2686dc392ad: Download complete 
Digest: sha256:370b54b572e7244cfd131571da39a49bcbd9cb0589828515ff3a1638e5cfad42
Status: Downloaded newer image for devopsinfra/docker-terragrunt:aws-tf-1.8.4-tg-0.58.12


root@dccc5e271843:/data# cd /app
root@dccc5e271843:/app# terraform init

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of alekc/kubectl from the dependency lock file
- Installing alekc/kubectl v2.0.4...
- Installed alekc/kubectl v2.0.4 (self-signed, key ID 772FB27A86DAFCE7)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

Terraform has made some changes to the provider dependency selections recorded
in the .terraform.lock.hcl file. Review those changes and commit them to your
version control system if they represent changes you intended to make.

Terraform has been successfully initialized!



# without passing AWS profile 
root@dccc5e271843:/app# terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # kubectl_manifest.example["static/secret.yaml"] will be created
  + resource "kubectl_manifest" "example" {
      + api_version             = "v1"
      + apply_only              = false
      + field_manager           = "kubectl"
      + force_conflicts         = false
      + force_new               = false
      + id                      = (known after apply)
      + kind                    = "Secret"
      + live_manifest_incluster = (sensitive value)
      + live_uid                = (known after apply)
      + name                    = "secret-basic-auth"
      + namespace               = "default"
      + server_side_apply       = false
      + uid                     = (known after apply)
      + validate_schema         = true
      + wait_for_rollout        = true
      + yaml_body               = (sensitive value)
      + yaml_body_parsed        = <<-EOT
            apiVersion: v1
            data: (sensitive value)
            kind: Secret
            metadata:
              name: secret-basic-auth
              namespace: default
            stringData: (sensitive value)
            type: Opaque
        EOT
      + yaml_incluster          = (sensitive value)
    }

  # kubectl_manifest.example["static/secret2.yaml"] will be created
  + resource "kubectl_manifest" "example" {
      + api_version             = "v1"
      + apply_only              = false
      + field_manager           = "kubectl"
      + force_conflicts         = false
      + force_new               = false
      + id                      = (known after apply)
      + kind                    = "Secret"
      + live_manifest_incluster = (sensitive value)
      + live_uid                = (known after apply)
      + name                    = "secret-basic-auth2"
      + namespace               = "default"
      + server_side_apply       = false
      + uid                     = (known after apply)
      + validate_schema         = true
      + wait_for_rollout        = true
      + yaml_body               = (sensitive value)
      + yaml_body_parsed        = <<-EOT
            apiVersion: v1
            data: (sensitive value)
            kind: Secret
            metadata:
              name: secret-basic-auth2
              namespace: default
            stringData: (sensitive value)
            type: Opaque
        EOT
      + yaml_incluster          = (sensitive value)
    }

Plan: 2 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

kubectl_manifest.example["static/secret.yaml"]: Creating...
kubectl_manifest.example["static/secret2.yaml"]: Creating...
╷
│ Error: default/secret-basic-auth2 failed to create kubernetes rest client for update of resource: Get "https://xxx.gr7.us-east-1.eks.amazonaws.com/api?timeout=32s": getting credentials: exec: executable aws failed with exit code 253
│ 
│   with kubectl_manifest.example["static/secret2.yaml"],
│   on main.tf line 34, in resource "kubectl_manifest" "example":
│   34: resource "kubectl_manifest" "example" {
│ 




root@dccc5e271843:/app# export AWS_PROFILE=xxxxxxx-dev2
root@dccc5e271843:/app# terraform apply --auto-approve

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # kubectl_manifest.example["static/secret.yaml"] will be created
  + resource "kubectl_manifest" "example" {
      + api_version             = "v1"
      + apply_only              = false
      + field_manager           = "kubectl"
      + force_conflicts         = false
      + force_new               = false
      + id                      = (known after apply)
      + kind                    = "Secret"
      + live_manifest_incluster = (sensitive value)
      + live_uid                = (known after apply)
      + name                    = "secret-basic-auth"
      + namespace               = "default"
      + server_side_apply       = false
      + uid                     = (known after apply)
      + validate_schema         = true
      + wait_for_rollout        = true
      + yaml_body               = (sensitive value)
      + yaml_body_parsed        = <<-EOT
            apiVersion: v1
            data: (sensitive value)
            kind: Secret
            metadata:
              name: secret-basic-auth
              namespace: default
            stringData: (sensitive value)
            type: Opaque
        EOT
      + yaml_incluster          = (sensitive value)
    }

  # kubectl_manifest.example["static/secret2.yaml"] will be created
  + resource "kubectl_manifest" "example" {
      + api_version             = "v1"
      + apply_only              = false
      + field_manager           = "kubectl"
      + force_conflicts         = false
      + force_new               = false
      + id                      = (known after apply)
      + kind                    = "Secret"
      + live_manifest_incluster = (sensitive value)
      + live_uid                = (known after apply)
      + name                    = "secret-basic-auth2"
      + namespace               = "default"
      + server_side_apply       = false
      + uid                     = (known after apply)
      + validate_schema         = true
      + wait_for_rollout        = true
      + yaml_body               = (sensitive value)
      + yaml_body_parsed        = <<-EOT
            apiVersion: v1
            data: (sensitive value)
            kind: Secret
            metadata:
              name: secret-basic-auth2
              namespace: default
            stringData: (sensitive value)
            type: Opaque
        EOT
      + yaml_incluster          = (sensitive value)
    }

Plan: 2 to add, 0 to change, 0 to destroy.
kubectl_manifest.example["static/secret.yaml"]: Creating...
kubectl_manifest.example["static/secret2.yaml"]: Creating...
kubectl_manifest.example["static/secret2.yaml"]: Creation complete after 2s [id=/api/v1/namespaces/default/secrets/secret-basic-auth2]
kubectl_manifest.example["static/secret.yaml"]: Creation complete after 2s [id=/api/v1/namespaces/default/secrets/secret-basic-auth]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
root@dccc5e271843:/app# 

```

This is the tf code
```hcl

terraform {
  required_providers {
    kubectl = {
      source = "alekc/kubectl"
      version = "2.0.4"
    }
  }
}

provider "kubectl" {
  host                   = local.host
  cluster_ca_certificate = local.ca

  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    args        = ["eks", "get-token", "--cluster-name", local.cluster_name]
  }
}

locals {
  files = { for fileName in fileset(path.module, "static/**/[a-z]*.yaml") : fileName => templatefile("${path.module}/${fileName}", {}) }
}

resource "kubectl_manifest" "example" {
  for_each = local.files
  yaml_body = each.value
}
```

Not sure whats causing an issue on your side. Does `aws sts get-caller-identity` work as expected from within your container?

**Comment by Kartoshnikov** [comment] 2024-08-06 10:31
@alekc 
Yes, AWS CLI works fine inside the container. There are no problems with all other providers which use the exec plugin, namely helm and kubernetes.
The only difference I see is the way resources were created.
If gavinbunney and this provider are the exac copies, then the root cause might be the fact of provider change.
All my resources were created with gavinbunney one, then I changed it to alekc in terraform section and ran `plan`. Here were problems began to appear. If I change the provider prefix in terrafrom section from alekc back to gavinbunney, it works right away.

I did try renaming the provider in my state file, but it didn't make any difference unfortunatelly.
I'm not the only one who finds migrating from gavinbunney to alekc provider problematic. And I'm not saying that something is wrong with the provider itself. The only goal I'm pursuing is to get it work.

**Comment by sinkr** [comment] 2024-08-07 13:38
This plugin is clearly problematic hence there is good reason.; the Helm plugin does not exhibit this issue. 

Users are telling you this yet you refuse to listen.

I am abandoning your plugin and will apply manifesta another way.

**Comment by alekc** [comment] 2024-08-07 14:12
If you create a fork of a helmet plugin, create some resources with
original one and then try to simply change to a forked one you will have
the same issue. Exec plugin works in clean test environment as proved by
tests above. But please feel free to do as you wish.

**Comment by alekc** [comment] 2024-08-19 10:06
Closing this off, since by the look of it the issue was caused by incorrect migration as mentioned above @Kartoshnikov feel free to reopen if that was not the case.

**Closed by alekc** 2024-08-19 10:06 UTC
Labels: invalid
